### ISSUE TITLE
Parágrafos longos

### ISSUE THREAD

**Issue by dagagny** [kelvinbiffi/MarioTextGeneratorJSPlugin#1]
A quantidade de caracteres por paragrafo poderia ser menos.

**Comment by kelvinbiffi** [comment]
Hey what do you think about this solution https://github.com/kelvinbiffi/MarioTextGeneratorJSPlugin/commit/6b35ccce1958d1b3da86a55d23d072df347c2824 you can test applied feature by the link https://kelvinbiffi.github.io/MarioTextGeneratorJSPlugin/ =)
